def estabelecimento():
    colunas = [
        'CNPJ BÁSICO',
        'CNPJ ORDEM',
        'CNPJ DV',
        'IDENTIFICADOR MATRIZ/FILIAL',
        'NOME FANTASIA',
        'SITUAÇÃO CADASTRAL',
        'DATA SITUAÇÃO CADASTRAL',
        'MOTIVO SITUAÇÃO CADASTRAL',
        'NOME DA CIDADE NO EXTERIOR',
        'PAIS',
        'DATA DE INÍCIO ATIVIDADE',
        'CNAE FISCAL PRINCIPAL',
        'CNAE FISCAL SECUNDÁRIA',
        'TIPO DE LOGRADOURO',
        'LOGRADOURO',
        'NÚMERO',
        'COMPLEMENTO',
        'BAIRRO',
        'CEP',
        'UF',
        'MUNICÍPIO',
        'DDD 1',
        'TELEFONE 1',
        'DDD 2', 
        'TELEFONE 2',
        'DDD DO FAX',
        'FAX',
        'CORREIO ELETRÔNICO',
        'SITUAÇÃO ESPECIAL',
        'DATA DA SITUAÇÃO ESPECIAL'
    ]